Rscript /opt/ichorCNA/scripts/runIchorCNA.R \
  --id tumor_sample \
  --WIG /opt/tumor.wig \
  --ploidy "c(2,3)" \
  --normal "c(0.5,0.6,0.7,0.8,0.9)" \
  --maxCN 5 \
  --gcWig /opt/ichorCNA/inst/extdata/gc_hg19_1000kb.wig \
  --mapWig /opt/ichorCNA/inst/extdata/map_hg19_1000kb.wig \
  --centromere /opt/ichorCNA/inst/extdata/GRCh37.p13_centromere_UCSC-gapTable.txt \
  --normalPanel /opt/ichorCNA/inst/extdata/HD_ULP_PoN_1Mb_median_normAutosome_mapScoreFiltered_median.rds \
  --includeHOMD False \
  --chrs "c(1:22, \"X\")" \
  --chrTrain "c(1:22)" \
  --estimateNormal True \
  --estimatePloidy True \
  --estimateScPrevalence True \
  --scStates "c(1,3)" \
  --txnE 0.9999 \
  --txnStrength 10000 \
  --genomeStyle "UCSC" \
  --outDir ./